### ISSUE TITLE
由于一个无法识别的目录,git pull拉取不了最新版

### ISSUE THREAD

**Issue by hhaoao** [snakeleon/YouCompleteMe-x64#5]
系统：win 10 64bit
命令行工具：cmder
git版本：
```cmd
λ git --version
git version 2.20.1.windows.1
```

使用`git pull`更新时，发现如下错误：

```cmd
λ git pull
error: The following untracked working tree files would be overwritten by merge:
        python/ycm/tests/testdata/uni¢�d€\tags
Please move or remove them before you merge.
Aborting
Updating 207a631f..2dbf4c14
```

照着[此链接](https://stackoverflow.com/questions/17404316/the-following-untracked-working-tree-files-would-be-overwritten-by-merge-but-i)操作发现无法识别那个乱码目录。

```cmd
git add ./python/ycm/tests/testdata/uni¢�d€/tags
fatal: pathspec './python/ycm/tests/testdata/uni¢�d€/tags' did no
t match any files
```

最后使用`git status`命令确认落后了6个commits.

```cmd
λ git status
On branch master
Your branch is behind 'origin/master' by 6 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
```

* What actually happened?
我想确认是不是就我出现这问题，希望能提供个办法处理这问题。

**Comment by snakeleon** [comment]
删除本地乱码的这个目录，再拉取解决问题。 SiFe ( Snake.Leon ) QQ: 26481904 BLOG: https://snakeleon.github.io GitHub: https://github.com/snakeleon 在2019年12月17日 21:23，hhaoao 写道： 系统：win 10 64bit 命令行工具：cmder git版本： λ git --version

git version 2.20.1.windows.1 使用git pull更新时，发现如下错误： λ git pull

error: The following untracked working tree files would be overwritten by merge:

        python/ycm/tests/testdata/uni¢�d€\tags

Please move or remove them before you merge.

Aborting

Updating 207a631f..2dbf4c14 照着此链接操作发现无法识别那个乱码目录。 git add ./python/ycm/tests/testdata/uni¢�d€/tags

fatal: pathspec './python/ycm/tests/testdata/uni¢�d€/tags' did no

t match any files 最后使用git status命令确认落后了6个commits. λ git status

On branch master

Your branch is behind 'origin/master' by 6 commits, and can be fast-forwarded.

  (use "git pull" to update your local branch)



nothing to commit, working tree clean What actually happened? 我想确认是不是就我出现这问题，希望能提供个办法处理这问题。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hhaoao** [comment]
虽然这样可以暂时解决，但是这次更新还是拉取了这个文件夹，自我感觉下次更新还是得手动删除。。。

**Comment by snakeleon** [comment]
用如下操作强制覆盖本地仓库代码
只是下载远程内容，不做任何合并
   
    git fetch --all

把HEAD指向刚下载的最新版本

    git reset --hard origin/master

**Comment by hhaoao** [comment]
非常感谢
